use crate::widget::Widget;

pub(crate) const MATRIX_WIDTH: usize = 9;
pub(crate) const MATRIX_HEIGHT: usize = 34;
pub(crate) type Matrix = [[u8; MATRIX_WIDTH]; MATRIX_HEIGHT];

/// Encode a boolean matrix into the protocol's packed 39-byte payload.
///
/// The source of truth for this shape is the Framework LED matrix hardware:
/// 9 columns x 34 rows = 306 bits, which packs into 39 bytes.
pub fn encode(arr: [[bool; MATRIX_WIDTH]; MATRIX_HEIGHT]) -> [u8; 39] {
    debug_assert_eq!(
        MATRIX_WIDTH * MATRIX_HEIGHT,
        306,
        "hardware protocol defines exactly 306 LEDs (9x34)"
    );

    let mut out_arr: [u8; 39] = [0; 39];
    let mut index = 0;
    let mut byte_offs = 0;

    #[allow(clippy::needless_range_loop)]
    for i in 0..MATRIX_HEIGHT {
        for j in 0..MATRIX_WIDTH {
            let newval = if arr[i][j] { 0x01 } else { 0x00 };
            out_arr[index] |= newval << byte_offs;

            index = if byte_offs >= 7 { index + 1 } else { index };
            byte_offs = if byte_offs >= 7 { 0 } else { byte_offs + 1 };
        }
    }

    out_arr
}

/// Transpose the matrix so rows become columns for serial writes.
pub fn transpose(arr: Matrix) -> [[u8; MATRIX_HEIGHT]; MATRIX_WIDTH] {
    let mut out = [[0; MATRIX_HEIGHT]; MATRIX_WIDTH];

    #[allow(clippy::needless_range_loop)]
    for i in 0..MATRIX_HEIGHT {
        for j in 0..MATRIX_WIDTH {
            out[j][i] = arr[i][j];
        }
    }

    out
}

/// Overlay a widget matrix on top of the full panel matrix at `(x, y)`.
pub fn emplace(orig: Matrix, widget: &dyn Widget, x: usize, y: usize) -> Matrix {
    let mut out: Matrix = orig;
    let shape = widget.get_shape();
    let width = shape.x;
    let height = shape.y;

    debug_assert_eq!(
        widget.get_matrix().len(),
        width * height,
        "widget matrix is generated by widget update() with width*height cells"
    );
    debug_assert!(
        x + width <= MATRIX_WIDTH,
        "main::validate_widget_placements ensures widget x+width fits 9-column hardware"
    );
    debug_assert!(
        y + height <= MATRIX_HEIGHT,
        "main::validate_widget_placements ensures widget y+height fits 34-row hardware"
    );

    if x + width > MATRIX_WIDTH || y + height > MATRIX_HEIGHT {
        return out;
    }

    for row in 0..height {
        for col in 0..width {
            out[row + y][col + x] = widget.get_matrix()[col + (width * row)];
        }
    }

    out
}
